version: '2.1'

networks:

  gwnet:
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/16
          ip_range: 172.30.0.0/24

  clients:
    enable_ipv6: true
    internal: true
    ipam:
      driver: default
      config:
        - subnet: fd30:252e:b4f5::/64
          ip_range: fd30:252e:b4f5:0:1::/80
        - subnet: 172.29.0.0/24
          ip_range: 172.29.0.0/24
          gateway: 172.29.0.1

services:

  nat64:
    image: creatordev/docker-nat64
    privileged: true
    stdin_open: true
    networks:
      gwnet:
        ipv4_address: 172.30.0.2
      clients:
        ipv4_address: 172.29.0.2

  contiki:
    build:
      context: .
    privileged: true
    stdin_open: true
    environment:
      TARGET: minimal-net
      PSK_IDENTITY: ""
      PSK_SECRET_KEY: ""
    networks:
      clients: {}
      gwnet: {}
    working_dir: /build/examples/awa-lwm2m
    volumes:
      - "../../:/build"
    depends_on:
    - nat64
    ports:
      - '3000:3000'
      - '1022:22'
